name: Update Football Matches

on:
  schedule:
    # يعمل كل 15 دقيقة لتحديث النتائج والحالات المباشرة طوال اليوم (يستهلك 96 طلب يومياً)
    - cron: '*/15 * * * *'
  workflow_dispatch: 

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        # تم إضافة pytz هنا لكي لا يفشل سكريبت البايثون
        run: pip install requests pytz

      - name: Run Scraper Script
        env:
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
        run: python fetch_matches.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add today_matches.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "تحديث مباريات اليوم أوتوماتيكياً" && git push)
